import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

function photo(id: string) {
  return `https://images.unsplash.com/${id}?auto=format&fit=crop&w=800&h=800&q=80`;
}

function portrait(kind: "men" | "women", n: number) {
  return `https://randomuser.me/api/portraits/${kind}/${n}.jpg`;
}

function presentationKind(name: string): "men" | "women" {
  return women.has(name) || transWomen.has(name) || transfem.has(name) ? "women" : "men";
}

function uniqueMedia(people: { name: string; email: string }[]) {
  let men = 0;
  let women = 0;
  const used = new Set<string>();
  const byEmail = new Map<string, { image: string; photos: string }>();

  function takeCover(name: string, email: string) {
    const kind = presentationKind(name);
    let url: string;
    if (kind === "women" && women <= 99) {
      url = portrait("women", women++);
    } else if (kind === "men" && men <= 99) {
      url = portrait("men", men++);
    } else if (men <= 99) {
      url = portrait("men", men++);
    } else if (women <= 99) {
      url = portrait("women", women++);
    } else {
      url = `https://picsum.photos/seed/${encodeURIComponent(`cover-${email}`)}/800/800`;
    }
    used.add(url);
    return url;
  }

  for (const person of people) {
    const image = takeCover(person.name, person.email);
    const extras: string[] = [];
    for (let slot = 0; extras.length < 5; slot++) {
      const url = `https://picsum.photos/seed/${encodeURIComponent(`${person.email}-extra-${slot}`)}/800/800`;
      if (used.has(url) || url === image) continue;
      used.add(url);
      extras.push(url);
    }
    byEmail.set(person.email, { image, photos: JSON.stringify([image, ...extras]) });
  }
  return byEmail;
}

const women = new Set([
  "Maya",
  "Priya",
  "Elena",
  "Amina",
  "Ivy",
  "Tess",
  "Chloe",
  "Jade",
  "Lana",
  "Nina",
  "Zara",
  "Freya",
  "Amara",
  "Yuki",
  "Rosa",
  "Dahlia",
  "Kira",
  "Pilar",
  "Hana",
  "Soleil",
  "Nia",
  "Anika",
  "Mei",
  "Imani",
  "Celine",
  "Talia",
  "Sofia",
  "Lucia",
  "Nadia",
  "Esme",
  "Ines",
  "Gemma",
  "Bella",
  "Nora",
  "Aisha",
  "Leila",
  "Sienna",
  "Olivia",
  "Hannah",
  "Grace",
  "Violet",
  "Avery",
  "Harper",
  "Skye",
  "Riley",
]);

const nonbinary = new Set(["Jordan", "Sasha", "Noor", "Wren", "Quinn", "Rowan", "Sage", "River"]);
const transMen = new Set(["Kai", "Finn", "Asher", "Ellis"]);
const transWomen = new Set(["Jade", "Hana", "Celine", "Marley"]);
const transmasc = new Set(["Theo", "Drew"]);
const transfem = new Set(["Ivy", "Phoenix"]);

const intoRotation = [
  "Men",
  "Women",
  "Everyone",
  "Men, Women",
  "Trans men",
  "Trans women",
  "Non-binary people",
  "Men, Trans men",
  "Women, Trans women",
];

const tribePool = [
  "Bear",
  "Cub",
  "Daddy",
  "Twink",
  "Twunk",
  "Otter",
  "Wolf",
  "Jock",
  "Geek",
  "Rugged",
  "Clean-cut",
  "Leather",
  "Discrete",
  "Poz",
  "Sober",
  "Queer",
  "Trans",
];

function identityFor(name: string) {
  const gender = transMen.has(name)
    ? "Trans man"
    : transWomen.has(name)
      ? "Trans woman"
      : transmasc.has(name)
        ? "Transmasculine"
        : transfem.has(name)
          ? "Transfeminine"
          : nonbinary.has(name)
            ? "Non-binary"
            : women.has(name)
              ? "Woman"
              : "Man";
  const n = name.split("").reduce((sum, char) => sum + char.charCodeAt(0), 0);
  const firstTribe = tribePool[n % tribePool.length];
  const secondTribe = tribePool[(n * 5) % tribePool.length];
  const tribes = firstTribe === secondTribe ? firstTribe : `${firstTribe}, ${secondTribe}`;
  return { gender, into: intoRotation[n % intoRotation.length], tribes };
}

function album(primary: string, extras: string[]) {
  return JSON.stringify([primary, ...extras.filter((url) => url !== primary)].slice(0, 6));
}

const nearbyPeople = [
  {
    name: "Alex",
    email: "alex@example.com",
    age: 28,
    city: "Soho",
    latitude: 51.5138,
    longitude: -0.1324,
    headline: "Gym + design. Say hi.",
    about: "Product designer who lives at the gym and the espresso bar. Looking for something easy and real.",
    lookingFor: "Dates",
    interests: "gym, design, coffee",
    isOnline: true,
    isBoosted: true,
    minutesAgo: 2,
    image: photo("photo-1500648767791-00dcc994a43e"),
  },
  {
    name: "Maya",
    email: "maya@example.com",
    age: 27,
    city: "Covent Garden",
    latitude: 51.5122,
    longitude: -0.124,
    headline: "Just got off work",
    about: "Product designer. Thoughtful conversations, city walks, and a decent negroni.",
    lookingFor: "Right now",
    interests: "design, walks, wine",
    isOnline: true,
    isBoosted: true,
    minutesAgo: 1,
    image: photo("photo-1494790108377-be9c29b29330"),
  },
  {
    name: "Jordan",
    email: "jordan@example.com",
    age: 31,
    city: "Fitzrovia",
    latitude: 51.5198,
    longitude: -0.1374,
    headline: "Here for the weekend",
    about: "Visiting from Manchester. Show me a good bar or a bad decision.",
    lookingFor: "Chat",
    interests: "travel, music, food",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 8,
    image: photo("photo-1507003211169-0a1dd7228f2d"),
  },
  {
    name: "Priya",
    email: "priya@example.com",
    age: 29,
    city: "Mayfair",
    latitude: 51.5104,
    longitude: -0.1472,
    headline: "Brunch or chaos",
    about: "Startup operator. Soft spot for late dinners and people who actually text back.",
    lookingFor: "Dates",
    interests: "startups, wellness, travel",
    isOnline: false,
    isBoosted: false,
    minutesAgo: 54,
    image: photo("photo-1534528741775-53994a69daeb"),
  },
  {
    name: "Leo",
    email: "leo@example.com",
    age: 26,
    city: "Chinawhite",
    latitude: 51.5116,
    longitude: -0.1358,
    headline: "Online now",
    about: "Photographer. If you can sit still for a portrait, we can probably get along.",
    lookingFor: "Friends",
    interests: "photo, film, nightlife",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 4,
    image: photo("photo-1506794778202-cad84cf45f1d"),
  },
  {
    name: "Sasha",
    email: "sasha@example.com",
    age: 24,
    city: "Soho",
    latitude: 51.5146,
    longitude: -0.1298,
    headline: "New in the area",
    about: "Just moved. Need a local who knows where the good late food is.",
    lookingFor: "Friends",
    interests: "food, art, dancing",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 12,
    image: photo("photo-1524504388940-b1c1722653e1"),
  },
  {
    name: "Marcus",
    email: "marcus@example.com",
    age: 33,
    city: "Fitzrovia",
    latitude: 51.5184,
    longitude: -0.1408,
    headline: "Coffee after this?",
    about: "Backend engineer. Quiet until I am not. Dark roast, long walks, no small talk about crypto.",
    lookingFor: "Dates",
    interests: "coffee, running, code",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 18,
    image: photo("photo-1492562080023-ab3db95bfbce"),
  },
  {
    name: "Noor",
    email: "noor@example.com",
    age: 30,
    city: "Marylebone",
    latitude: 51.5188,
    longitude: -0.1502,
    headline: "Free for an hour",
    about: "Architect. I notice buildings and people who dress like they mean it.",
    lookingFor: "Right now",
    interests: "architecture, jazz, design",
    isOnline: true,
    isBoosted: true,
    minutesAgo: 6,
    image: photo("photo-1488426862026-3ee34a7d66df"),
  },
  {
    name: "Dylan",
    email: "dylan@example.com",
    age: 25,
    city: "Covent Garden",
    latitude: 51.5111,
    longitude: -0.1222,
    headline: "Indie games + ramen",
    about: "Building a tiny game. Will talk about it too much if you let me.",
    lookingFor: "Chat",
    interests: "games, ramen, synths",
    isOnline: false,
    isBoosted: false,
    minutesAgo: 95,
    image: photo("photo-1539571696357-5a69c17a67c6"),
  },
  {
    name: "Elena",
    email: "elena@example.com",
    age: 28,
    city: "South Bank",
    latitude: 51.5062,
    longitude: -0.1164,
    headline: "By the river",
    about: "Gallery girl. Prefer people who can walk without staring at their phone.",
    lookingFor: "Dates",
    interests: "art, river walks, books",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 22,
    image: photo("photo-1529626455594-4ff0802cfb7e"),
  },
  {
    name: "Kai",
    email: "kai@example.com",
    age: 27,
    city: "Soho",
    latitude: 51.5124,
    longitude: -0.1336,
    headline: "Low key tonight",
    about: "Private, respectful, around the corner. No drama.",
    lookingFor: "Right now",
    interests: "tech, gym, nightlife",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 3,
    image: photo("photo-1519085360753-af0119f7cbe7"),
  },
  {
    name: "Amina",
    email: "amina@example.com",
    age: 26,
    city: "Bloomsbury",
    latitude: 51.5206,
    longitude: -0.1274,
    headline: "Bookshop date?",
    about: "PhD-adjacent. I will recommend a novel and then forget to text. Still worth it.",
    lookingFor: "Dates",
    interests: "books, museums, tea",
    isOnline: false,
    isBoosted: false,
    minutesAgo: 140,
    image: photo("photo-1517841905240-472988babdf9"),
  },
  {
    name: "Nate",
    email: "nate@example.com",
    age: 34,
    city: "King's Cross",
    latitude: 51.5306,
    longitude: -0.1238,
    headline: "Just landed",
    about: "In town two nights. If you know a rooftop, lead the way.",
    lookingFor: "Chat",
    interests: "travel, wine, rooftops",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 11,
    image: photo("photo-1504257432389-52343af06ae3"),
  },
  {
    name: "Ivy",
    email: "ivy@example.com",
    age: 23,
    city: "Shoreditch",
    latitude: 51.5258,
    longitude: -0.0804,
    headline: "Fresh profile",
    about: "New here. DJs on Thursdays. Looking for people who actually leave the house.",
    lookingFor: "Friends",
    interests: "music, vintage, clubs",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 9,
    image: photo("photo-1531746020798-e6953c6e8e04"),
  },
  {
    name: "Omar",
    email: "omar@example.com",
    age: 32,
    city: "Angel",
    latitude: 51.5322,
    longitude: -0.1062,
    headline: "Dinner plans open",
    about: "Chef on my nights off. I cook better than I text.",
    lookingFor: "Dates",
    interests: "food, football, vinyl",
    isOnline: false,
    isBoosted: false,
    minutesAgo: 210,
    image: photo("photo-1463453091185-61582044d556"),
  },
  {
    name: "Tess",
    email: "tess@example.com",
    age: 29,
    city: "Clerkenwell",
    latitude: 51.5228,
    longitude: -0.1036,
    headline: "After-work drink",
    about: "Editor. Dry humor, wet streets, and one more round.",
    lookingFor: "Dates",
    interests: "writing, pubs, film",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 27,
    image: photo("photo-1520813792240-56fc4a3765a7"),
  },
  {
    name: "Ravi",
    email: "ravi@example.com",
    age: 30,
    city: "Holborn",
    latitude: 51.5174,
    longitude: -0.1198,
    headline: "Walking through",
    about: "Lawyer by day. Looking for someone who does not want to talk about work.",
    lookingFor: "Chat",
    interests: "running, jazz, travel",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 16,
    image: photo("photo-1488161628813-04466f872be2"),
  },
  {
    name: "Chloe",
    email: "chloe@example.com",
    age: 25,
    city: "Camden",
    latitude: 51.539,
    longitude: -0.1426,
    headline: "Market until 6",
    about: "Stylist. If you can keep up around Camden, we will get along.",
    lookingFor: "Friends",
    interests: "fashion, markets, gigs",
    isOnline: false,
    isBoosted: false,
    minutesAgo: 80,
    image: photo("photo-1544005313-94ddf0286df2"),
  },
  {
    name: "Felix",
    email: "felix@example.com",
    age: 36,
    city: "Mayfair",
    latitude: 51.5096,
    longitude: -0.1494,
    headline: "Hotel bar later",
    about: "In finance, out of excuses. Looking for a grown-up night.",
    lookingFor: "Dates",
    interests: "wine, travel, art",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 33,
    image: photo("photo-1522556189639-b150ed9c4330"),
  },
  {
    name: "Jade",
    email: "jade@example.com",
    age: 27,
    city: "Brick Lane",
    latitude: 51.5204,
    longitude: -0.0716,
    headline: "Bagels then maybe",
    about: "Illustrator. Soft launch energy. Hard launch if you are funny.",
    lookingFor: "Chat",
    interests: "drawing, bagels, film",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 19,
    image: photo("photo-1487412720507-e7ab37603c6f"),
  },
  {
    name: "Theo",
    email: "theo@example.com",
    age: 22,
    city: "Bloomsbury",
    latitude: 51.5242,
    longitude: -0.1306,
    headline: "Student. Don't judge.",
    about: "Last year. I know every cheap lunch within a mile of campus.",
    lookingFor: "Friends",
    interests: "uni, cycling, gigs",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 7,
    image: photo("photo-1501196354995-cbb51c65aaea"),
  },
  {
    name: "Lana",
    email: "lana@example.com",
    age: 31,
    city: "Kensington",
    latitude: 51.501,
    longitude: -0.1932,
    headline: "West tonight",
    about: "Galleries, long coats, and people who show up when they say they will.",
    lookingFor: "Dates",
    interests: "art, pilates, travel",
    isOnline: false,
    isBoosted: false,
    minutesAgo: 300,
    image: photo("photo-1502823403499-6ccfcf4fb453"),
  },
  {
    name: "Samir",
    email: "samir@example.com",
    age: 29,
    city: "Waterloo",
    latitude: 51.5032,
    longitude: -0.1132,
    headline: "Crossing the river",
    about: "Sound engineer. I will notice the playlist before I notice anything else.",
    lookingFor: "Right now",
    interests: "music, nights out, coffee",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 14,
    image: photo("photo-1531123897727-8f129e1688ce"),
  },
  {
    name: "Luca",
    email: "luca@example.com",
    age: 28,
    city: "Soho",
    latitude: 51.5132,
    longitude: -0.1348,
    headline: "Two streets over",
    about: "Bartender. I get off at 1. That is not a metaphor unless you want it to be.",
    lookingFor: "Right now",
    interests: "bars, vinyl, late food",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 5,
    image: portrait("men", 11),
  },
  {
    name: "Nina",
    email: "nina@example.com",
    age: 26,
    city: "Fitzrovia",
    latitude: 51.5202,
    longitude: -0.1352,
    headline: "New photos up",
    about: "Set designer. If you can carry a plant home on the tube, we can date.",
    lookingFor: "Dates",
    interests: "theatre, plants, wine",
    isOnline: true,
    isBoosted: true,
    minutesAgo: 3,
    image: portrait("women", 12),
  },
  {
    name: "Ben",
    email: "ben@example.com",
    age: 32,
    city: "Covent Garden",
    latitude: 51.5126,
    longitude: -0.1228,
    headline: "Just around the piazza",
    about: "Lighting tech. Nights are loud. Mornings are coffee and silence.",
    lookingFor: "Chat",
    interests: "theatre, coffee, cycling",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 9,
    image: portrait("men", 22),
  },
  {
    name: "Zara",
    email: "zara@example.com",
    age: 24,
    city: "Shoreditch",
    latitude: 51.5266,
    longitude: -0.0812,
    headline: "Fresh tonight",
    about: "Makeup artist. I will notice your collarbones before your job title.",
    lookingFor: "Friends",
    interests: "makeup, clubs, film",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 6,
    image: portrait("women", 21),
  },
  {
    name: "Hugo",
    email: "hugo@example.com",
    age: 35,
    city: "Mayfair",
    latitude: 51.5108,
    longitude: -0.146,
    headline: "Hotel gym then drinks",
    about: "In town for work. Looking for someone who can pick a bar without a spreadsheet.",
    lookingFor: "Dates",
    interests: "travel, gym, whisky",
    isOnline: false,
    isBoosted: false,
    minutesAgo: 70,
    image: portrait("men", 33),
  },
  {
    name: "Freya",
    email: "freya@example.com",
    age: 29,
    city: "Angel",
    latitude: 51.5314,
    longitude: -0.1054,
    headline: "Canal walk?",
    about: "Nurse. Off tomorrow. Want someone who can talk without performing.",
    lookingFor: "Dates",
    interests: "swimming, baking, canals",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 15,
    image: portrait("women", 32),
  },
  {
    name: "Cole",
    email: "cole@example.com",
    age: 27,
    city: "Holborn",
    latitude: 51.5178,
    longitude: -0.1184,
    headline: "Between meetings",
    about: "Policy nerd. I promise I am more fun in person than that sounds.",
    lookingFor: "Chat",
    interests: "politics, running, pubs",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 12,
    image: portrait("men", 44),
  },
  {
    name: "Amara",
    email: "amara@example.com",
    age: 30,
    city: "Brixton",
    latitude: 51.4613,
    longitude: -0.1156,
    headline: "South of the river",
    about: "Radio producer. I will interview you by accident. That is a compliment.",
    lookingFor: "Dates",
    interests: "radio, dancing, jerk chicken",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 20,
    image: portrait("women", 36),
  },
  {
    name: "Sean",
    email: "sean@example.com",
    age: 31,
    city: "Camden",
    latitude: 51.5402,
    longitude: -0.1438,
    headline: "Lockside now",
    about: "Tour manager. In London three nights. Show me your city.",
    lookingFor: "Right now",
    interests: "gigs, vans, breakfast",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 4,
    image: portrait("men", 52),
  },
  {
    name: "Yuki",
    email: "yuki@example.com",
    age: 25,
    city: "Bloomsbury",
    latitude: 51.5218,
    longitude: -0.1288,
    headline: "Study break",
    about: "Masters student. I know every quiet corner of the British Library.",
    lookingFor: "Friends",
    interests: "study, tea, film",
    isOnline: false,
    isBoosted: false,
    minutesAgo: 110,
    image: portrait("women", 47),
  },
  {
    name: "Malik",
    email: "malik@example.com",
    age: 28,
    city: "King's Cross",
    latitude: 51.5312,
    longitude: -0.1252,
    headline: "Platform side",
    about: "Courier by day, photographer when the light is good.",
    lookingFor: "Chat",
    interests: "bikes, photos, night rides",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 8,
    image: portrait("men", 61),
  },
  {
    name: "Rosa",
    email: "rosa@example.com",
    age: 33,
    city: "Clerkenwell",
    latitude: 51.5234,
    longitude: -0.1022,
    headline: "Wine bar open",
    about: "Sommelier. I will not judge your order. I will remember it.",
    lookingFor: "Dates",
    interests: "wine, Italian, jazz",
    isOnline: true,
    isBoosted: true,
    minutesAgo: 7,
    image: portrait("women", 55),
  },
  {
    name: "Finn",
    email: "finn@example.com",
    age: 23,
    city: "Soho",
    latitude: 51.5142,
    longitude: -0.1318,
    headline: "New here",
    about: "Just moved from Dublin. Need a local and a decent pint.",
    lookingFor: "Friends",
    interests: "football, pubs, gigs",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 2,
    image: portrait("men", 67),
  },
  {
    name: "Dahlia",
    email: "dahlia@example.com",
    age: 27,
    city: "Notting Hill",
    latitude: 51.5094,
    longitude: -0.1962,
    headline: "Portobello until dusk",
    about: "Vintage dealer. If you can spot a good jacket, we already have a date.",
    lookingFor: "Dates",
    interests: "vintage, markets, dogs",
    isOnline: false,
    isBoosted: false,
    minutesAgo: 88,
    image: portrait("women", 64),
  },
  {
    name: "Owen",
    email: "owen@example.com",
    age: 34,
    city: "South Bank",
    latitude: 51.5054,
    longitude: -0.1172,
    headline: "By the bookshop",
    about: "Playwright. I rewrite texts more than I send them.",
    lookingFor: "Chat",
    interests: "theatre, river, coffee",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 25,
    image: portrait("men", 71),
  },
  {
    name: "Kira",
    email: "kira@example.com",
    age: 26,
    city: "Peckham",
    latitude: 51.4742,
    longitude: -0.0694,
    headline: "Rooftop later",
    about: "Ceramicist. Hands always a little dusty. Worth it.",
    lookingFor: "Right now",
    interests: "clay, rooftops, dancing",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 11,
    image: portrait("women", 68),
  },
  {
    name: "Andre",
    email: "andre@example.com",
    age: 29,
    city: "Dalston",
    latitude: 51.5462,
    longitude: -0.0756,
    headline: "Kingsland Road",
    about: "DJ. I will play one more track. Then maybe another.",
    lookingFor: "Friends",
    interests: "house, radios, night buses",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 13,
    image: portrait("men", 75),
  },
  {
    name: "Pilar",
    email: "pilar@example.com",
    age: 31,
    city: "Marylebone",
    latitude: 51.5192,
    longitude: -0.1516,
    headline: "Free after six",
    about: "Physio. I will tell you to stretch and then suggest a cocktail.",
    lookingFor: "Dates",
    interests: "pilates, tapas, parks",
    isOnline: false,
    isBoosted: false,
    minutesAgo: 160,
    image: portrait("women", 73),
  },
  {
    name: "Miles",
    email: "miles@example.com",
    age: 36,
    city: "Canary Wharf",
    latitude: 51.5054,
    longitude: -0.0235,
    headline: "East after work",
    about: "Trader who would rather talk about food than markets.",
    lookingFor: "Dates",
    interests: "food, running, jazz",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 18,
    image: portrait("men", 78),
  },
  {
    name: "Hana",
    email: "hana@example.com",
    age: 24,
    city: "Chinawhite",
    latitude: 51.512,
    longitude: -0.1366,
    headline: "Out tonight",
    about: "Host. I know every door person on this street. That is not a flex. Okay it is.",
    lookingFor: "Right now",
    interests: "nights out, fashion, karaoke",
    isOnline: true,
    isBoosted: true,
    minutesAgo: 1,
    image: portrait("women", 79),
  },
  {
    name: "Craig",
    email: "craig@example.com",
    age: 38,
    city: "Islington",
    latitude: 51.5364,
    longitude: -0.1032,
    headline: "Upper Street",
    about: "Teacher. Weeknights are early. Weekends are not.",
    lookingFor: "Dates",
    interests: "books, hiking, Sunday roast",
    isOnline: false,
    isBoosted: false,
    minutesAgo: 240,
    image: portrait("men", 81),
  },
  {
    name: "Soleil",
    email: "soleil@example.com",
    age: 27,
    city: "Hackney",
    latitude: 51.545,
    longitude: -0.0554,
    headline: "Park then pub",
    about: "Florist. I will put flowers in your kitchen without asking.",
    lookingFor: "Friends",
    interests: "flowers, parks, natural wine",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 16,
    image: portrait("women", 82),
  },
  {
    name: "Dev",
    email: "dev@example.com",
    age: 30,
    city: "Old Street",
    latitude: 51.5256,
    longitude: -0.0876,
    headline: "Roundabout nearby",
    about: "Startup guy trying not to sound like a startup guy.",
    lookingFor: "Chat",
    interests: "startups, gym, dumplings",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 10,
    image: portrait("men", 84),
  },
  {
    name: "Nia",
    email: "nia@example.com",
    age: 28,
    city: "Pimlico",
    latitude: 51.4894,
    longitude: -0.1336,
    headline: "By the Tate",
    about: "Curator. I walk through rooms slower than most people. Come with me.",
    lookingFor: "Dates",
    interests: "art, walking, jazz",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 22,
    image: portrait("women", 85),
  },
  {
    name: "Rhys",
    email: "rhys@example.com",
    age: 26,
    city: "Waterloo",
    latitude: 51.5038,
    longitude: -0.1144,
    headline: "Station adjacent",
    about: "Sound guy. I will fix your aux cable and your night.",
    lookingFor: "Right now",
    interests: "gigs, trains, coffee",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 6,
    image: portrait("men", 86),
  },
  {
    name: "Anika",
    email: "anika@example.com",
    age: 32,
    city: "Hampstead",
    latitude: 51.556,
    longitude: -0.178,
    headline: "Heath then home",
    about: "GP. Looking for someone who likes long walks and short texts.",
    lookingFor: "Dates",
    interests: "heath, cooking, piano",
    isOnline: false,
    isBoosted: false,
    minutesAgo: 190,
    image: portrait("women", 88),
  },
  {
    name: "Pablo",
    email: "pablo@example.com",
    age: 29,
    city: "Borough",
    latitude: 51.5044,
    longitude: -0.0912,
    headline: "Market close",
    about: "Cheesemonger. I will feed you something you cannot pronounce.",
    lookingFor: "Friends",
    interests: "food, markets, football",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 14,
    image: portrait("men", 88),
  },
  {
    name: "Mei",
    email: "mei@example.com",
    age: 25,
    city: "Chinatown",
    latitude: 51.5114,
    longitude: -0.1312,
    headline: "Noodles first",
    about: "I will take you to the good place. It does not have a queue on purpose.",
    lookingFor: "Chat",
    interests: "noodles, karaoke, film",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 5,
    image: portrait("women", 90),
  },
  {
    name: "Grant",
    email: "grant@example.com",
    age: 41,
    city: "Kensington",
    latitude: 51.5004,
    longitude: -0.1924,
    headline: "West side",
    about: "Gallery owner. Looking for someone who stays for the second drink.",
    lookingFor: "Dates",
    interests: "art, travel, sailing",
    isOnline: false,
    isBoosted: false,
    minutesAgo: 320,
    image: portrait("men", 90),
  },
  {
    name: "Imani",
    email: "imani@example.com",
    age: 27,
    city: "Brixton",
    latitude: 51.4624,
    longitude: -0.1142,
    headline: "Electric tonight",
    about: "Dancer. If you can keep time, we already like each other.",
    lookingFor: "Right now",
    interests: "dance, afrobeat, food",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 8,
    image: portrait("women", 91),
  },
  {
    name: "Vito",
    email: "vito@example.com",
    age: 33,
    city: "Soho",
    latitude: 51.5136,
    longitude: -0.1304,
    headline: "Espresso in 10",
    about: "I run a tiny coffee counter. Come stand in the way and talk to me.",
    lookingFor: "Chat",
    interests: "espresso, scooters, football",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 3,
    image: portrait("men", 92),
  },
  {
    name: "Celine",
    email: "celine@example.com",
    age: 30,
    city: "Fitzrovia",
    latitude: 51.519,
    longitude: -0.1392,
    headline: "After this meeting",
    about: "Brand strategist. I turn everything into a bit. Including this.",
    lookingFor: "Dates",
    interests: "design, negronis, travel",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 17,
    image: portrait("women", 93),
  },
  {
    name: "Asher",
    email: "asher@example.com",
    age: 24,
    city: "Camden",
    latitude: 51.5382,
    longitude: -0.1412,
    headline: "Market stall till 5",
    about: "I sell records. If you flip past the first crate we cannot be friends.",
    lookingFor: "Friends",
    interests: "vinyl, skate, street food",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 9,
    image: portrait("men", 93),
  },
  {
    name: "Talia",
    email: "talia@example.com",
    age: 28,
    city: "Bethnal Green",
    latitude: 51.5274,
    longitude: -0.0558,
    headline: "Park picnic energy",
    about: "Community chef. I cook for too many people and still have leftovers.",
    lookingFor: "Dates",
    interests: "cooking, parks, radio",
    isOnline: false,
    isBoosted: false,
    minutesAgo: 75,
    image: portrait("women", 94),
  },
  {
    name: "Reza",
    email: "reza@example.com",
    age: 31,
    city: "Edgware Road",
    latitude: 51.5204,
    longitude: -0.1694,
    headline: "Shisha or dinner",
    about: "I know the late kitchens. That is my whole personality after 11.",
    lookingFor: "Right now",
    interests: "food, football, nights out",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 4,
    image: portrait("men", 95),
  },
  {
    name: "Wren",
    email: "wren@example.com",
    age: 26,
    city: "London Fields",
    latitude: 51.5416,
    longitude: -0.0614,
    headline: "Lido then pints",
    about: "I swim outdoors even when it is a bad idea. Join at your own risk.",
    lookingFor: "Friends",
    interests: "swimming, pubs, illustration",
    isOnline: true,
    isBoosted: false,
    minutesAgo: 12,
    image: portrait("women", 96),
  },
];

const extraPeople = [
  ["Sofia", 26, "Shoreditch", 51.526, -0.078, "Dates", true, 3],
  ["Tomas", 30, "Dalston", 51.548, -0.076, "Right now", true, 6],
  ["Lucia", 28, "Islington", 51.536, -0.103, "Chat", false, 40],
  ["Nico", 27, "Angel", 51.532, -0.106, "Friends", true, 9],
  ["Nadia", 32, "King's Cross", 51.531, -0.124, "Dates", true, 2],
  ["Adrian", 29, "Bloomsbury", 51.522, -0.128, "Chat", false, 55],
  ["Esme", 24, "Clerkenwell", 51.523, -0.107, "Right now", true, 11],
  ["Callum", 33, "Barbican", 51.52, -0.095, "Dates", true, 14],
  ["Ines", 31, "Bank", 51.513, -0.089, "Friends", false, 70],
  ["Ewan", 28, "London Bridge", 51.505, -0.086, "Chat", true, 5],
  ["Gemma", 27, "Bermondsey", 51.498, -0.081, "Dates", true, 18],
  ["Louis", 34, "Peckham", 51.474, -0.069, "Right now", false, 90],
  ["Bella", 25, "Brixton", 51.462, -0.115, "Friends", true, 7],
  ["Mateo", 29, "Stockwell", 51.472, -0.122, "Dates", true, 21],
  ["Nora", 30, "Clapham", 51.462, -0.138, "Chat", false, 48],
  ["Hassan", 32, "Battersea", 51.477, -0.148, "Right now", true, 4],
  ["Aisha", 26, "Chelsea", 51.487, -0.169, "Dates", true, 16],
  ["Ibrahim", 35, "Fulham", 51.477, -0.201, "Friends", false, 110],
  ["Leila", 29, "Hammersmith", 51.492, -0.224, "Chat", true, 13],
  ["Jaden", 24, "Shepherd's Bush", 51.505, -0.226, "Right now", true, 8],
  ["Sienna", 27, "Notting Hill", 51.516, -0.197, "Dates", false, 62],
  ["Kyle", 31, "Paddington", 51.515, -0.176, "Friends", true, 19],
  ["Olivia", 28, "Marylebone", 51.522, -0.157, "Chat", true, 10],
  ["Mason", 26, "Regent's Park", 51.531, -0.157, "Dates", false, 77],
  ["Hannah", 33, "Camden", 51.541, -0.143, "Right now", true, 1],
  ["Noah", 29, "Chalk Farm", 51.544, -0.153, "Friends", true, 22],
  ["Grace", 25, "Kentish Town", 51.55, -0.141, "Dates", false, 51],
  ["Oscar", 36, "Tufnell Park", 51.557, -0.138, "Chat", true, 15],
  ["Violet", 27, "Highbury", 51.552, -0.102, "Right now", true, 12],
  ["Patrick", 30, "Stoke Newington", 51.562, -0.074, "Dates", false, 84],
  ["Avery", 26, "Hackney", 51.545, -0.055, "Friends", true, 6],
  ["Ruben", 32, "Homerton", 51.547, -0.043, "Chat", true, 17],
  ["Harper", 28, "Bow", 51.527, -0.017, "Dates", false, 66],
  ["Stefan", 34, "Canary Wharf", 51.505, -0.023, "Right now", true, 3],
  ["Skye", 24, "Greenwich", 51.477, 0.0, "Friends", true, 25],
  ["Victor", 29, "Deptford", 51.478, -0.026, "Dates", false, 93],
  ["Riley", 27, "New Cross", 51.475, -0.037, "Chat", true, 9],
  ["Will", 31, "Lewisham", 51.461, -0.012, "Friends", true, 28],
  ["Quinn", 26, "Brockley", 51.464, -0.037, "Dates", false, 58],
  ["Yusuf", 33, "Whitechapel", 51.516, -0.059, "Right now", true, 4],
  ["Rowan", 25, "Spitalfields", 51.52, -0.075, "Chat", true, 11],
  ["Ellis", 29, "Hoxton", 51.531, -0.081, "Friends", false, 44],
  ["Marley", 27, "Old Street", 51.526, -0.087, "Dates", true, 2],
  ["Drew", 30, "Farringdon", 51.52, -0.105, "Right now", true, 8],
  ["Phoenix", 24, "Holborn", 51.517, -0.12, "Chat", false, 71],
  ["Sage", 28, "Temple", 51.511, -0.114, "Friends", true, 20],
  ["River", 26, "South Bank", 51.507, -0.117, "Dates", true, 5],
  ["Casey", 32, "Waterloo", 51.503, -0.114, "Right now", false, 39],
  ["Ari", 25, "Vauxhall", 51.486, -0.123, "Chat", true, 7],
  ["Blake", 31, "Kennington", 51.488, -0.11, "Friends", true, 16],
  ["Cameron", 29, "Elephant & Castle", 51.495, -0.1, "Dates", false, 81],
  ["Peyton", 27, "Borough", 51.504, -0.091, "Right now", true, 6],
  ["Taylor", 34, "Monument", 51.511, -0.086, "Chat", true, 13],
  ["Jamie", 28, "Aldgate", 51.514, -0.076, "Friends", false, 47],
  ["Morgan", 30, "Liverpool Street", 51.518, -0.081, "Dates", true, 9],
].map((row, index) => {
  const [name, age, city, latitude, longitude, lookingFor, isOnline, minutesAgo] = row as [
    string,
    number,
    string,
    number,
    number,
    string,
    boolean,
    number,
  ];
  const kind = women.has(name) || nonbinary.has(name) || transfem.has(name) || transWomen.has(name) ? "women" : "men";
  return {
    name,
    email: `${name.toLowerCase()}.${index}@pidge.dating`,
    age,
    city,
    latitude,
    longitude,
    headline: isOnline ? "Online now" : "Around later",
    about: `Based in ${city}. ${lookingFor === "Right now" ? "Free tonight." : "Open to seeing who is nearby."}`,
    lookingFor,
    interests: "nights out, gym, music",
    isOnline,
    isBoosted: index % 9 === 0,
    minutesAgo,
    image: portrait(kind, (index % 90) + 1),
  };
});

const allPeople = [...nearbyPeople, ...extraPeople];
const media = uniqueMedia([
  { name: "Play Reviewer", email: "play@pidge.dating" },
  { name: "Chris", email: "test@example.com" },
  ...allPeople,
]);

async function main() {
  const wipe = process.env.SEED_WIPE !== "0";
  if (wipe) {
    await prisma.message.deleteMany();
    await prisma.conversation.deleteMany();
    await prisma.meetupRequest.deleteMany();
    await prisma.account.deleteMany();
    await prisma.session.deleteMany();
    await prisma.user.deleteMany();
  }

  const passwordHash = await bcrypt.hash("password123", 12);

  const playMedia = media.get("play@pidge.dating")!;
  const chrisMedia = media.get("test@example.com")!;

  await prisma.user.upsert({
    where: { email: "play@pidge.dating" },
    update: { image: playMedia.image, photos: playMedia.photos },
    create: {
      name: "Play Reviewer",
      email: "play@pidge.dating",
      passwordHash,
      bio: "Google Play review account. 18+.",
      city: "Soho",
      latitude: 51.5136,
      longitude: -0.1365,
      interests: "review",
      timezone: "GMT",
      availability: "Anytime",
      age: 28,
      headline: "Play reviewer",
      lookingFor: "Friends",
      gender: "Man",
      into: "Everyone",
      tribes: "Geek",
      lastActiveAt: new Date(),
      isOnline: true,
      isBoosted: false,
      profileComplete: true,
      membershipTier: "unlimited",
      dateOfBirth: new Date("1998-01-15"),
      ageConfirmed: true,
      image: playMedia.image,
      photos: playMedia.photos,
    },
  });

  await prisma.user.upsert({
    where: { email: "test@example.com" },
    update: { image: chrisMedia.image, photos: chrisMedia.photos },
    create: {
      name: "Chris",
      email: "test@example.com",
      passwordHash,
      bio: "Building Pidge. Around Soho most evenings — say hi if you are close.",
      city: "Soho",
      latitude: 51.513,
      longitude: -0.131,
      interests: "design, coffee, nights out",
      timezone: "GMT",
      availability: "Tonight",
      age: 29,
      headline: "Here. Now.",
      lookingFor: "Dates",
      gender: "Man",
      into: "Everyone",
      tribes: "Geek, Jock",
      lastActiveAt: new Date(),
      isOnline: true,
      isBoosted: false,
      profileComplete: true,
      membershipTier: "free",
      image: chrisMedia.image,
      photos: chrisMedia.photos,
    },
  });

  await Promise.all(
    allPeople.map((person) => {
      const identity = identityFor(person.name);
      const data = {
        name: person.name,
        email: person.email,
        passwordHash,
        bio: person.about,
        city: person.city,
        latitude: person.latitude,
        longitude: person.longitude,
        interests: person.interests,
        timezone: "GMT",
        availability: person.isOnline ? "Now" : "Later",
        age: person.age,
        headline: person.headline,
        lookingFor: person.lookingFor,
        gender: identity.gender,
        into: identity.into,
        tribes: identity.tribes,
        lastActiveAt: new Date(Date.now() - person.minutesAgo * 60 * 1000),
        isOnline: person.isOnline,
        isBoosted: person.isBoosted,
        profileComplete: true,
        image: media.get(person.email)!.image,
        photos: media.get(person.email)!.photos,
      };
      return prisma.user.upsert({
        where: { email: person.email },
        update: data,
        create: data,
      });
    }),
  );

  const play = await prisma.user.findUnique({ where: { email: "play@pidge.dating" } });
  const alex = await prisma.user.findUnique({ where: { email: "alex@example.com" } });
  if (play && alex && wipe) {
    const [userAId, userBId] = play.id < alex.id ? [play.id, alex.id] : [alex.id, play.id];
    const conversation = await prisma.conversation.create({
      data: { userAId, userBId, lastText: "You nearby? Grab a drink." },
    });
    await prisma.message.createMany({
      data: [
        {
          conversationId: conversation.id,
          senderId: alex.id,
          body: "Hey — saw you on the grid. You nearby?",
        },
        {
          conversationId: conversation.id,
          senderId: play.id,
          body: "Yeah, Soho. You still out?",
        },
        {
          conversationId: conversation.id,
          senderId: alex.id,
          body: "You nearby? Grab a drink.",
        },
      ],
    });
    const last = await prisma.message.findFirst({
      where: { conversationId: conversation.id },
      orderBy: { createdAt: "desc" },
    });
    if (last) {
      await prisma.conversation.update({
        where: { id: conversation.id },
        data: { lastMessageAt: last.createdAt, lastText: last.body },
      });
    }
  }

  const total = await prisma.user.count({ where: { deletedAt: null } });
  console.log(`Seeded ${allPeople.length + 2} listed profiles. Database now has ${total} users.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
